# Generated by Django 5.0.6 on 2024-06-05 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('rol', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chiva',
            fields=[
                ('placa', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCuenta', models.IntegerField()),
                ('tipoCuente', models.CharField(max_length=100)),
                ('entidadBancaria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('puntoEquilibrio', models.IntegerField()),
                ('valorAumento', models.IntegerField()),
                ('fechaAumento', models.DateField()),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('rol', models.CharField(max_length=100)),
                ('cuentaBancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.cuentabancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Paseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('disponibilidad', models.IntegerField()),
                ('chiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.chiva')),
                ('esquemaCobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.esquemacobro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateField()),
                ('valor', models.IntegerField()),
                ('comprobantePago', models.CharField(max_length=200)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.paquete')),
                ('paseo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.paseo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.cliente')),
            ],
        ),
    ]
