# Generated by Django 5.0.6 on 2024-06-21 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=100, unique=True)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numCuenta', models.IntegerField()),
                ('tipoCuente', models.CharField(max_length=100)),
                ('entidadBancaria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EsquemaCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.IntegerField(default=0)),
                ('puntoEquilibrio', models.IntegerField()),
                ('valorAumento', models.IntegerField()),
                ('fechaAumento', models.DateField()),
                ('descuento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('valor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('edad', models.IntegerField()),
                ('rol', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('celular', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('edad', models.IntegerField()),
                ('rol', models.CharField(max_length=100)),
                ('cuentaBancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.cuentabancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Paseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(default='default_value', max_length=500000)),
                ('origen', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('disponibilidad', models.IntegerField()),
                ('chiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.chiva')),
                ('esquemaCobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.esquemacobro')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fechaCreacion', models.DateField()),
                ('valor', models.IntegerField()),
                ('comprobantePago', models.CharField(default='default_value', max_length=200000)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.paquete')),
                ('paseo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.paseo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Desembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('motivo', models.CharField(max_length=500)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.reserva')),
            ],
        ),
    ]
