# Generated by Django 5.0.6 on 2024-06-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paseo',
            name='imagen',
            field=models.CharField(default='default_value', max_length=500),
        ),
    ]
