# Generated by Django 5.0.6 on 2024-06-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desembolso',
            name='comprobante',
            field=models.CharField(default='default_value', max_length=200000),
        ),
        migrations.AddField(
            model_name='desembolso',
            name='estado',
            field=models.CharField(default='pendiente', max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comprobantePago',
            field=models.CharField(default='none', max_length=200000),
        ),
    ]
