# Generated by Django 5.0.6 on 2024-06-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseos', '0002_paseo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='esquemacobro',
            name='valor',
            field=models.IntegerField(default=0),
        ),
    ]
