# Generated by Django 5.0.6 on 2024-06-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseos', '0002_desembolso_comprobante_desembolso_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desembolso',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
