# Generated by Django 5.0.7 on 2024-07-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseos', '0003_alter_desembolso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rol',
            field=models.CharField(default='cliente', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='paquete',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='paseos.paquete'),
        ),
    ]
