# Generated by Django 5.0.6 on 2024-06-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paseos', '0004_administrador_is_active_administrador_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='contrasena',
        ),
    ]
