# Generated by Django 5.0.6 on 2024-06-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseos', '0006_administrador_groups_administrador_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('motivo', models.CharField(max_length=500)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paseos.reserva')),
            ],
        ),
    ]
