# Generated by Django 5.0.6 on 2024-06-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseos', '0010_alter_paseo_imagen_alter_reserva_comprobantepago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='comprobantePago',
            field=models.CharField(default='default_value', max_length=200000),
        ),
    ]
