# Generated by Django 5.0.6 on 2024-06-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paseos', '0012_alter_paseo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiva',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chiva',
            name='placa',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
